[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Cấu hình SPA redirect - chuyển hướng tất cả yêu cầu 404 về index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200