[build]
  base = ""
  command = "cd frontend && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "20"

# Cấu hình SPA redirect - chuyển hướng tất cả yêu cầu 404 về index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
